--Patrick Jensen (mxf667) & Frederik Jeppesen (wcn773)

DROP TABLE IF EXISTS Cus_rates_Res CASCADE;
DROP TABLE IF EXISTS Cus_rates_Cour CASCADE;
DROP TABLE IF EXISTS Makes CASCADE;
DROP TABLE IF EXISTS Receives CASCADE;
DROP TABLE IF EXISTS Couriers CASCADE;
DROP TABLE IF EXISTS Restaurants CASCADE;
DROP TABLE IF EXISTS Take_out_orders CASCADE;
DROP TABLE IF EXISTS Courier_orders CASCADE;
DROP TABLE IF EXISTS Food_orders CASCADE;
DROP TABLE IF EXISTS Customers CASCADE;
DROP TABLE IF EXISTS Meal_combinations CASCADE;
DROP TABLE IF EXISTS United_contracts CASCADE;